---
- name: creacion de usuarios Linux
  hosts: all
  tasks:

    - name: add user "jbrea"
      ansible.builtin.user:
        name: jbrea
        comment: jbrea
        group: sudo
        password: 'jjj081428'
        createhome: yes
        home: /home/jbrea
