---
- name: creacion de usuarios Linux prueba
  hosts: all
  tasks:

    - name: add user "pepe"
      ansible.builtin.user:
        name: pepe
        comment: jbrea
        group: sudo
        createhome: yes
        home: /home/pepe
